stages:
  - build
  - documentation

image:
  node:20

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'main'

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y build-essential python3 python3-pip

build:
  stage: build
  script:
    # Print the version of npm (for debugging)
    - npm --version
    # Install angular
    - npm install -g @angular/cli@15.2.7
    # Install dependencies
    - npm install
    # Build the application
    - npm run build

documentation:
  stage: documentation
  artifacts:
    paths:
      - docs/build/
    name: "display-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 1 week
    expose_as: 'sphinx documentation'
  script:
    # Install sphinx
    - pip3 install sphinx
    # Print the sphinx version (for debugging)
    - sphinx-build --version
    # Build the documentation
    - sphinx-build docs/source/ docs/build
